export const UPDATE_MAFIA_ROLES = "UPDATE_MAFIA_ROLES";
export const UPDATE_VILLAGE_ROLES = "UPDATE_VILLAGE_ROLES";
export const UPDATE_PLAYER_NAMES = "UPDATE_PLAYER_NAMES";
export const UPDATE_ALLOCATION = "UPDATE_ALLOCATION";
export const UPDATE_PLAYER_CHANNELS = "UPDATE_PLAYER_CHANNELS";
export const UPDATE_SLACK_API_KEY = "UPDATE_SLACK_KEY";
export const SHOW_TOAST = "SHOW_TOAST";
export const HIDE_TOAST = "HIDE_TOAST";
